# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-24 13:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('RedeemGamesWEB', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ControleEstoqueJogo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantChaves', models.BigIntegerField(verbose_name=1)),
                ('chaveAcesso', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Pergunta',
            fields=[
                ('idPergunta', models.AutoField(primary_key=True, serialize=False)),
                ('Pergunta', models.CharField(max_length=200)),
                ('Resposta', models.CharField(max_length=200)),
            ],
        ),
        migrations.RemoveField(
            model_name='bancomoedasusuario',
            name='idUsuario',
        ),
        migrations.RemoveField(
            model_name='pedido',
            name='idJogo',
        ),
        migrations.RemoveField(
            model_name='pedido',
            name='idUsuario',
        ),
        migrations.RemoveField(
            model_name='jogo',
            name='chaveAcesso',
        ),
        migrations.DeleteModel(
            name='BancoMoedasUsuario',
        ),
        migrations.DeleteModel(
            name='Pedido',
        ),
        migrations.DeleteModel(
            name='Usuario',
        ),
        migrations.AddField(
            model_name='controleestoquejogo',
            name='idJogo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='RedeemGamesWEB.Jogo'),
        ),
    ]
