# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-24 13:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RedeemGamesWEB', '0003_remove_controleestoquejogo_quantchaves'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ControleEstoqueJogo',
            new_name='JogoChave',
        ),
        migrations.AddField(
            model_name='jogo',
            name='descricaoJogo',
            field=models.CharField(default='DESCRIÇÃO', max_length=500),
        ),
    ]
