# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-26 05:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RedeemGamesWEB', '0006_postgamesite'),
    ]

    operations = [
        migrations.AddField(
            model_name='jogo',
            name='linkDownload',
            field=models.URLField(default=''),
        ),
    ]
